# EXAMPLES CAN BE FOUND HERE
# https://github.com/numpy/numpy/blob/master/.travis.yml

_docs_job: &docs_job
  addons:
    apt:
      update: false
      packages:
  cache: false
  before_install:
  install: pip install -r docs/requirements-docs.txt
  script:
    - travis-sphinx build --nowarn --source=docs

os: linux
dist: xenial
language: python

# Travis allows these packages, additions can be requested
#   https://github.com/travis-ci/apt-package-safelist
addons:
  apt:
    update: true        # runs `apt-get update` before installs
    packages:
      - portaudio19-dev # Install portaudio (requirement for pyaudio)
      - libudev-dev
      - python3-dev

jobs:
  fast_finish: true
  include:
    - python: "3.7"
      name: "Docs"
      dist: xenial
      <<: *docs_job
    - python: "3.7"
      dist: xenial
    - python: "3.8"
      dist: xenial
    - python: "3.9"
      dist: xenial

cache:
  directories:
    - $HOME/.cache/pip
    - "node_modules"

before_install:
  - nvm install 12  # Use nvm to install Node.js v12.x
  - pip install --upgrade pip wheel setuptools # Setup/upgrade pip/wheel/setuptools prior to install
#  - pip install codecov - for uploading unit tests when we make unit tests

install:
  - npm install -g yarn

script:
  # Build the frontend first
  - cd frontend
  - yarn
  - yarn build
  - cd ..
  # Then, build the backend
  - python setup.py bdist_wheel
  - pip install --pre --find-links=dist .

# after_success:
#    - codecov - for uploading unit tests when we make unit tests